version: '3'
services:
  strapi:
    container_name: strapi
    build: ./back
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./back/config:/opt/app/config
      - ./back/src:/opt/app/src
      - ./back/package.json:/opt/package.json
      - ./back/yarn.lock:/opt/yarn.lock
      - ./back/db:/opt/app/db

      - ./back/.env:/opt/app/.env
      - ./back/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
  front:
    container_name: front
    build: ./front
    image: front:latest
    ports:
      - 8000:80
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
